  
//job
export const GET_JOB_PENDING = "GET_JOB_PENDING";
export const GET_JOB_FULFILLED = "GET_JOB_FULFILLED";
export const GET_JOB_REJECTED = "GET_JOB_REJECTED";

export const ADD_JOB_PENDING = "ADD_JOB_PENDING";
export const ADD_JOB_FULFILLED = "ADD_JOB_FULFILLED";
export const ADD_JOB_REJECTED = "ADD_JOB_REJECTED";

export const EDIT_JOB_PENDING = "EDIT_JOB_PENDING";
export const EDIT_JOB_FULFILLED = "EDIT_JOB_FULFILLED";
export const EDIT_JOB_REJECTED = "EDIT_JOB_REJECTED";

export const REMOVE_JOB_PENDING = "REMOVE_JOB_PENDING";
export const REMOVE_JOB_FULFILLED = "REMOVE_JOB_FULFILLED";
export const REMOVE_JOB_REJECTED = "REMOVE_JOB";

//company
export const GET_COMPANY_PENDING = "GET_COMPANY_PENDING";
export const GET_COMPANY_FULFILLED = "GET_COMPANY_FULFILLED";
export const GET_COMPANY_REJECTED = "GET_COMPANY_REJECTED";

export const ADD_COMPANY_PENDING = "ADD_COMPANY_PENDING";
export const ADD_COMPANY_FULFILLED = "ADD_COMPANY_FULFILLED";
export const ADD_COMPANY_REJECTED = "ADD_COMPANY_REJECTED";

export const EDIT_COMPANY_PENDING = "EDIT_COMPANY_PENDING";
export const EDIT_COMPANY_FULFILLED = "EDIT_COMPANY_FULFILLED";
export const EDIT_COMPANY_REJECTED = "EDIT_COMPANY_REJECTED";

export const REMOVE_COMPANY_PENDING = "REMOVE_COMPANY_PENDING";
export const REMOVE_COMPANY_FULFILLED = "REMOVE_COMPANY_FULFILLED";
export const REMOVE_COMPANY_REJECTED = "REMOVE_COMPANY";