  
//job
export const GET_JOB_PENDING = "GET_JOB_PENDING";
export const GET_JOB_FULFILLED = "GET_JOB_FULFILLED";
export const GET_JOB_REJECTED = "GET_JOB_REJECTED";

export const ADD_JOB_PENDING = "ADD_JOB_PENDING";
export const ADD_JOB_FULFILLED = "ADD_JOB_FULFILLED";
export const ADD_JOB_REJECTED = "ADD_JOB_REJECTED";

export const UPDATE_JOB_PENDING = "UPDATE_JOB_PENDING";
export const UPDATE_JOB_FULFILLED = "UPDATE_JOB_FULFILLED";
export const UPDATE_JOB_REJECTED = "UPDATE_JOB_REJECTED";

export const DELETE_JOB_PENDING = "DELETE_JOB_PENDING";
export const DELETE_JOB_FULFILLED = "DELETE_JOB_FULFILLED";
export const DELETE_JOB_REJECTED = "DELETE_JOB_REJECTED";

//company
export const GET_COMPANY_PENDING = "GET_COMPANY_PENDING";
export const GET_COMPANY_FULFILLED = "GET_COMPANY_FULFILLED";
export const GET_COMPANY_REJECTED = "GET_COMPANY_REJECTED";

export const ADD_COMPANY_PENDING = "ADD_COMPANY_PENDING";
export const ADD_COMPANY_FULFILLED = "ADD_COMPANY_FULFILLED";
export const ADD_COMPANY_REJECTED = "ADD_COMPANY_REJECTED";

export const UPDATE_COMPANY_PENDING = "UPDATE_COMPANY_PENDING";
export const UPDATE_COMPANY_FULFILLED = "UPDATE_COMPANY_FULFILLED";
export const UPDATE_COMPANY_REJECTED = "UPDATE_COMPANY_REJECTED";

export const DELETE_COMPANY_PENDING = "DELETE_COMPANY_PENDING";
export const DELETE_COMPANY_FULFILLED = "DELETE_COMPANY_FULFILLED";
export const DELETE_COMPANY_REJECTED = "DELETE_COMPANY_REJECTED";

//user
export const GET_USER_PENDING = "GET_USER_PENDING";
export const GET_USER_FULFILLED = "GET_USER_FULFILLED";
export const GET_USER_REJECTED = "GET_USER_REJECTED";

export const ADD_USER_PENDING = "ADD_USER_PENDING";
export const ADD_USER_FULFILLED = "ADD_USER_FULFILLED";
export const ADD_USER_REJECTED = "ADD_USER_REJECTED";

export const UPDATE_USER_PENDING = "UPDATE_USER_PENDING";
export const UPDATE_USER_FULFILLED = "UPDATE_USER_FULFILLED";
export const UPDATE_USER_REJECTED = "UPDATE_USER_REJECTED";

export const DELETE_USER_PENDING = "DELETE_USER_PENDING";
export const DELETE_USER_FULFILLED = "DELETE_USER_FULFILLED";
export const DELETE_USER_REJECTED = "DELETE_USER_REJECTED";

export const LOGIN_USER_PENDING = "LOGIN_USER_PENDING";
export const LOGIN_USER_FULFILLED = "LOGIN_USER_FULFILLED";
export const LOGIN_USER_REJECTED = "LOGIN_USER_REJECTED";


//category
export const GET_CATEGORY_PENDING = "GET_CATEGORY_PENDING";
export const GET_CATEGORY_FULFILLED = "GET_CATEGORY_FULFILLED";
export const GET_CATEGORY_REJECTED = "GET_CATEGORY_REJECTED";

export const ADD_CATEGORY_PENDING = "ADD_CATEGORY_PENDING";
export const ADD_CATEGORY_FULFILLED = "ADD_CATEGORY_FULFILLED";
export const ADD_CATEGORY_REJECTED = "ADD_CATEGORY_REJECTED";

export const UPDATE_CATEGORY_PENDING = "UPDATE_CATEGORY_PENDING";
export const UPDATE_CATEGORY_FULFILLED = "UPDATE_CATEGORY_FULFILLED";
export const UPDATE_CATEGORY_REJECTED = "UPDATE_CATEGORY_REJECTED";

export const DELETE_CATEGORY_PENDING = "DELETE_CATEGORY_PENDING";
export const DELETE_CATEGORY_FULFILLED = "DELETE_CATEGORY_FULFILLED";
export const DELETE_CATEGORY_REJECTED = "DELETE_CATEGORY_REJECTED";